
local DC = DC or {}

DC.ANALYS_CUSTOM_TYPE_ALL = 1 --"全选",
DC.ANALYS_CUSTOM_TYPE_NOR = 2 --"通用选择",
--DC.ANALYS_CUSTOM_TYPE_LAST2 = 3 --"去除最新两期相同数",

DC.ANALYS_CUSTOM_TYPE_EVEN4_6 = 50 --"去除4~6连号",
DC.ANALYS_CUSTOM_TYPE_EVEN3 = 51 --"去除3连号",
DC.ANALYS_CUSTOM_TYPE_2EVEN_IN3 = 52 --"2组或以上\连号量有>2",
DC.ANALYS_CUSTOM_TYPE_INTERVAL4_6 = 53 --"去除连续4~6的间隔号"

DC.ANALYS_CUSTOM_TYPE_A_SINGLE = 100 --"去除全单",
DC.ANALYS_CUSTOM_TYPE_A_DOUBLE = 101 --"去除全双"
DC.ANALYS_CUSTOM_TYPE_SINGLE5 = 102 --"去除5单",
DC.ANALYS_CUSTOM_TYPE_DOUBLE5 = 103 --"去除5双",
--DC.ANALYS_CUSTOM_TYPE_SECTION = 11 --"区间选取",
--DC.ANALYS_CUSTOM_TYPE_R_SUM_OVER = 150 --"去除红球总和过145的",
--DC.ANALYS_CUSTOM_TYPE_R_SUM_LESS = 151 --"去除红球总和小于50的",

DC.ANALYS_CUSTOM_TYPE_LAST_SAME = 200 --过滤与最新期有3或以上相同
DC.ANALYS_CUSTOM_TYPE_LAST_BLUE = 201 --忽略上期蓝球

DC.ANALYS_CUSTOM_TYPE_SECTION_OVER = 251 --"过滤同区间5或以上组合",
DC.ANALYS_CUSTOM_TYPE_SECTION_OVER4 = 252 --过滤同区间4或以上组合 (大约占5%+5%)
DC.ANALYS_CUSTOM_TYPE_SECTION_1_2_IN3 = 253 --"分2组3个在1/2区间",
DC.ANALYS_CUSTOM_TYPE_SECTION_EACH_IN3 = 254 --"分2组3个在任意2区间",

DC.ANALYS_CUSTOM = {}
DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_ALL] = _TT("dc","DC12")
DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_NOR] = _TT("dc","DC13")

--DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_LAST2] = _TT("dc","DC17")
DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_EVEN4_6] = _TT("dc","DC14")
DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_EVEN3] = _TT("dc","DC18")
DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_2EVEN_IN3] = _TT("dc","DC19")
DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_INTERVAL4_6] = "去除连续4~6的间隔号"

DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_A_SINGLE] = _TT("dc","DC15")
DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_A_DOUBLE] = _TT("dc","DC16")
DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_SINGLE5] = _TT("dc","DC20")
DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_DOUBLE5] = _TT("dc","DC22")
--DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_SECTION] = _TT("dc","DC24")
-- DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_R_SUM_OVER] = _TT("dc","DC69")
-- DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_R_SUM_LESS] = _TT("dc","DC70")

DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_LAST_SAME] = _TT("dc","DC74")
--DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_LAST_BLUE] = _TT("dc","DC75")

DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_SECTION_OVER] = _TT("dc","DC73")
--DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_SECTION_OVER4] = _TT("dc","DC76")
--DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_SECTION_1_2_IN3] = _TT("dc","DC96")
--DC.ANALYS_CUSTOM[DC.ANALYS_CUSTOM_TYPE_SECTION_EACH_IN3] = _TT("dc","DC97")


DC.USEDEF_KEY = {}
DC.USEDEF_KEY.CONDITION = "CONDITION"
DC.USEDEF_KEY.CONDITION_SET = "CONDITION_SET"
DC.USEDEF_KEY.DRAW_RESULT = "DRAW_RESULT"


return DC