-- RefConfig.lua [08/22/16 19:16:39 ]

loadLuaFile("jackpot/res/ref/BagRef")
loadLuaFile("jackpot/res/ref/BuffRef")
loadLuaFile("jackpot/res/ref/BuildRef")
loadLuaFile("jackpot/res/ref/ChariotRef")
loadLuaFile("jackpot/res/ref/CheckPointRef")
loadLuaFile("jackpot/res/ref/CollectRef")
loadLuaFile("jackpot/res/ref/EquipRef")
loadLuaFile("jackpot/res/ref/GatherRef")
loadLuaFile("jackpot/res/ref/HeroRef")
loadLuaFile("jackpot/res/ref/HouseRef")
loadLuaFile("jackpot/res/ref/ItemRef")
loadLuaFile("jackpot/res/ref/MakeRef")
loadLuaFile("jackpot/res/ref/MonsterRef")
loadLuaFile("jackpot/res/ref/RefText_en_US")
loadLuaFile("jackpot/res/ref/RefText_zh_CN")
loadLuaFile("jackpot/res/ref/RoleRef")
loadLuaFile("jackpot/res/ref/ShopRef")
loadLuaFile("jackpot/res/ref/SkillRef")
loadLuaFile("jackpot/res/ref/TapConfig")
loadLuaFile("jackpot/res/ref/WorkerRef")
